### ISSUE TITLE
The app will shut down in the moment when I open it

### ISSUE THREAD

**Issue by windrises** [alseambusher/Paideia#1]
I downloaded the apk from the url you gived. But The app will shut down in the moment when I open it. I have try many times.
       Then I use the Android Studio to import the source code. It is builded successfully, but the app still shut down.
       I also build tensorflow on Ubuntu and build this app. It is builded successfully, but the app still shut down.
       I use the Android Studio to Debug. When the app shut down, the Android Studio logs shows this:
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.alse.paideia, PID: 25823
                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.alse.paideia-1/base.apk"],nativeLibraryDirectories=[/data/app/com.alse.paideia-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libpaideia.so"
                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at com.alse.paideia.TensorflowClassifier.<clinit>(TensorflowClassifier.java:48)
                      at com.alse.paideia.TensorflowImageListener.<init>(TensorflowImageListener.java:56)
                      at com.alse.paideia.CameraConnectionFragment.<init>(CameraConnectionFragment.java:557)
                      at com.alse.paideia.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:262)
                      at com.alse.paideia.MainActivity.onCreate(MainActivity.java:56)
                      at android.app.Activity.performCreate(Activity.java:6303)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                      at android.app.ActivityThread.access$900(ActivityThread.java:153)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
`

**Comment by LtveG** [comment]
I have the same error....Do you solve it?

**Comment by vivekjm** [comment]
i have that same error also..can anyone help me
